# Generated by Django 4.0.4 on 2022-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
