# Generated by Django 4.0.4 on 2022-04-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='foto_noticia',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
